services:
  - type: web
    name: student-api
    env: go
    plan: free
    buildCommand: go build -o main .
    startCommand: ./main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
