services:
- type: web
  name: student-api
  runtime: go
  repo: https://github.com/sonukumar1722/fealtyX
  plan: free
  envVars:
  - key: PORT
    sync: false
  region: oregon
  buildCommand: go build -o main .
  startCommand: ./main
  autoDeployTrigger: commit
version: "1"
